#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains
#       the string Ceci n'est pas une page


# Create a new configuration file for custom 404 page
sudo tee /etc/nginx/sites-available/default
server {
    listen 80;
    server_name _;

    location / {
        return 404 "Ceci n'est pas une page\n";
    }

    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }

}
EOF

# Create a symbolic link to enable the new configuration
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Create the custom 404 HTML page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Test Nginx configuration for syntax errors
sudo nginx -t

# Reload Nginx to apply changes
sudo service nginx restart

