#!/usr/bin/env bash
# Set up server 2
# Install nginx
sudo apt-get -y update
sudo apt-get install nginx

# Make file
sudo mkdir -p /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i "25i add_header X-Served-By \$hostname;" /etc/nginx/nginx.conf
sudo service nginx reload
sudo service nginx restart
