#!/usr/bin/env bash
# Install and configure HAproxy on lb-o1 server

CFG="\\\nlisten appname bind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 224424-web-01 52.91.125.119 check\n\tserver 224424-web-02 34.227.94.173 check\n"

sudo apt-get -y update
sudo apt-get -y install haproxy=2.5*

echo "$CFG" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
