#!/usr/bin/env bash
# Install and configure HAProxy load balancer

sudo apt-get -y update
sudo apt-get install -y haproxy=2.0.\*

# Config load balancer with web servers
echo  "\nfrontend load_balancer\n\tbind\t*:80\n\tmode\thttp\n\tdefault_backend\tweb_servers\n\nbackend web_servers\n\tbalance\troundrobin\n\tserver\t224424-web-01\t52.91.125.119\n\tserver\t224424-web-02\t52.86.30.214" | /etc/haproxy/haproxy.cfg

# Enable load balancer
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy


sudo service haproxy start
