#!/usr/bin/env bash

# intalls fireall; block all incoming except ports 22, 80, 443
sudo apt-get -y  install ufw
sudo sed -i "s/IPV6=no/IPV6=yes/" /etc/default/ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming

# configure ports access
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https

# activate the firewall
sudo ufw enable
