#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user

# Change file permissions of config file
chmod 644 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/ngix.conf

# update config file with user 'nginx'
sudo sed -i 's/#user www-data;/user nginx;/g"'/etc/nginx/nginx.conf

# Update file to listen to port 8080
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default

# netstat -lpn shows apache2 is using 8080
pkill 'apache2'

# Restart nginx
sudo -u nginx service nginx restart

